/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `SS_posts` VALUES
(2,1,"2020-05-03 10:58:15","2020-05-03 09:58:15","<!-- wp:paragraph -->\n<p>This is an example page. It\'s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:quote -->\n<blockquote class=\"wp-block-quote\"><p>Hi there! I\'m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin\' caught in the rain.)</p></blockquote>\n<!-- /wp:quote -->\n\n<!-- wp:paragraph -->\n<p>...or something like this:</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:quote -->\n<blockquote class=\"wp-block-quote\"><p>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</p></blockquote>\n<!-- /wp:quote -->\n\n<!-- wp:paragraph -->\n<p>As a new WordPress user, you should go to <a href=\"http://dockswp.local/wp-admin/\">your dashboard</a> to delete this page and create new pages for your content. Have fun!</p>\n<!-- /wp:paragraph -->","Home","","publish","closed","closed","","home","","","2020-05-03 11:02:40","2020-05-03 10:02:40","",0,"http://dockswp.local/?page_id=2",0,"page","",0),
(3,1,"2020-05-03 10:58:15","2020-05-03 09:58:15","","Privacy Policy","","publish","closed","open","","privacy-policy","","","2020-05-03 11:03:31","2020-05-03 10:03:31","",0,"http://dockswp.local/?page_id=3",0,"page","",0),
(4,1,"2020-05-03 10:58:28","0000-00-00 00:00:00","","Auto Draft","","auto-draft","open","open","","","","","2020-05-03 10:58:28","0000-00-00 00:00:00","",0,"http://dockswp.local/?p=4",0,"post","",0),
(5,1,"2020-05-03 11:02:40","2020-05-03 10:02:40","<!-- wp:paragraph -->\n<p>This is an example page. It\'s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:quote -->\n<blockquote class=\"wp-block-quote\"><p>Hi there! I\'m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin\' caught in the rain.)</p></blockquote>\n<!-- /wp:quote -->\n\n<!-- wp:paragraph -->\n<p>...or something like this:</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:quote -->\n<blockquote class=\"wp-block-quote\"><p>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</p></blockquote>\n<!-- /wp:quote -->\n\n<!-- wp:paragraph -->\n<p>As a new WordPress user, you should go to <a href=\"http://dockswp.local/wp-admin/\">your dashboard</a> to delete this page and create new pages for your content. Have fun!</p>\n<!-- /wp:paragraph -->","Home","","inherit","closed","closed","","2-revision-v1","","","2020-05-03 11:02:40","2020-05-03 10:02:40","",2,"https://dockswp.local/uncategorised/2-revision-v1/",0,"revision","",0),
(6,1,"2020-05-03 11:03:31","2020-05-03 10:03:31","","Privacy Policy","","inherit","closed","closed","","3-revision-v1","","","2020-05-03 11:03:31","2020-05-03 10:03:31","",3,"https://dockswp.local/uncategorised/3-revision-v1/",0,"revision","",0);
